language: php
php:
    - '7.2'
    - '7.3'
    - nightly

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

script:
    - vendor/bin/phpunit
    - vendor/bin/phpstan analyse src --level=7
    - vendor/bin/phpcs --standard=psr2 --extensions=php src tests

notifications:
    email: false
