version: "3.7"
services:
    squirrel_queries_test:
        image: thecodingmachine/php:8.1-v4-cli
        container_name: squirrel_queries_test
        tty: true
        working_dir: /usr/src/app
        command: ["vendor/bin/phpunit", "--colors=always", "--filter", "Integration"]
        volumes:
            - ./src:/usr/src/app/src
            - ./tests:/usr/src/app/tests
            - ./composer.json:/usr/src/app/composer.json
            - ./phpunit.xml.dist:/usr/src/app/phpunit.xml.dist
            - ./vendor-bin:/usr/src/app/vendor-bin
        environment:
            PHP_EXTENSION_APCU: 0
            PHP_EXTENSION_REDIS: 0
            PHP_EXTENSION_SQLITE3: 1
            PHP_EXTENSION_PDO_MYSQL: 1
            PHP_EXTENSION_PDO_PGSQL: 1
            PHP_EXTENSION_PDO_SQLITE: 1
            PHP_INI_MEMORY_LIMIT: 1g
            PHP_INI_ERROR_REPORTING: E_ALL
            SQUIRREL_TEST_SQLITE: 'sqlite:///:memory:'
            SQUIRREL_TEST_POSTGRES: 'postgres://user:password@squirrel_queries_postgres/postgres?charset=UTF-8'
            SQUIRREL_TEST_MYSQL: 'mysql://user:password@squirrel_queries_mysql/shop'
            SQUIRREL_TEST_MARIADB: 'mysql://user:password@squirrel_queries_mariadb/shop'
            STARTUP_COMMAND_1: composer update --no-scripts --no-plugins --quiet
        depends_on:
            - squirrel_queries_postgres
            - squirrel_queries_mysql
            - squirrel_queries_mariadb

    squirrel_queries_postgres:
        image: postgres:latest
        container_name: squirrel_queries_postgres
        environment:
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'

    squirrel_queries_mysql:
        image: mysql/mysql-server:latest
        container_name: squirrel_queries_mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'whatever'
            MYSQL_DATABASE: 'shop'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'

    squirrel_queries_mariadb:
        image: mariadb:latest
        container_name: squirrel_queries_mariadb
        environment:
            MARIADB_ROOT_PASSWORD: 'whatever'
            MARIADB_DATABASE: 'shop'
            MARIADB_USER: 'user'
            MARIADB_PASSWORD: 'password'