#!/usr/bin/env bash
# Get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Remove all running docker containers
docker-compose -f "$DIR/compose/coverage.yml" --project-directory "$DIR/.." down --volumes --remove-orphans

# Test SQLite and real live tests with PostgreSQL and MySQL
docker-compose -f "$DIR/compose/coverage.yml" --project-directory "$DIR/.." up --build --force-recreate --renew-anon-volumes --remove-orphans --always-recreate-deps --abort-on-container-exit --exit-code-from=coverage coverage

# Remove all running docker containers
docker-compose -f "$DIR/compose/coverage.yml" --project-directory "$DIR/.." down --volumes --remove-orphans