#!/usr/bin/env bash
# Get directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Pull new docker images in case there were updates
docker-compose -f "$DIR/compose-test.yml" --project-directory "$DIR/.." pull
docker-compose -f "$DIR/compose-coverage.yml" --project-directory "$DIR/.." pull