services:
    composer:
        image: thecodingmachine/php:8.2-v4-cli
        container_name: squirrel_queries_composer
        working_dir: /usr/src/app
        command: [ "composer", "${COMPOSER_COMMAND}", "--ansi" ]
        logging:
            driver: "none"
        volumes:
            - ./.editorconfig:/usr/src/app/.editorconfig
            - ./.git:/usr/src/app/.git
            - ./bin:/usr/src/app/bin
            - ./composer.json:/usr/src/app/composer.json
            - ./composer.lock:/usr/src/app/composer.lock
            - ./src:/usr/src/app/src
            - ./tests:/usr/src/app/tests
            - ./tools:/usr/src/app/tools
            - ./vendor:/usr/src/app/vendor
            - ./vendor-bin:/usr/src/app/vendor-bin
            - "$HOME/.cache/composer:/tmp/composer_cache"
        environment:
            COMPOSER_CACHE_DIR: "/tmp/composer_cache"
            COMPOSER_ROOT_VERSION: 'dev-master'
            # Basic config for CLI commands
            PHP_INI_ERROR_REPORTING: "E_ALL"
            PHP_INI_MEMORY_LIMIT: "1g"
            PHP_INI_MAX_EXECUTION_TIME: 3600
            # Enable Opcache + JIT
            PHP_INI_OPCACHE__ENABLE_CLI: 1
            PHP_INI_OPCACHE__MEMORY_CONSUMPTION: 256
            PHP_INI_OPCACHE__VALIDATE_TIMESTAMPS: 0
            PHP_INI_JIT_BUFFER_SIZE: "256m"