services:
    coverage:
        image: thecodingmachine/php:8.4-v4-cli
        container_name: squirrel_queries_coverage
        tty: true
        working_dir: /usr/src/app
        # --path-coverage could be added later, it is much too slow currently and only supported by xdebug
        command: [ "vendor/bin/phpunit", "--configuration=tools/phpunit.xml.dist", "--colors=always", "--stop-on-defect", "--coverage-html", "tests/_reports"]
        volumes:
            - ./composer.json:/usr/src/app/composer.json
            - ./src:/usr/src/app/src
            - ./tests:/usr/src/app/tests
            - ./tools:/usr/src/app/tools
            - ./vendor:/usr/src/app/vendor
        environment:
            # We currently use PCOV because it is at least 8x faster
            # - 3 seconds compared to 23 seconds (or 5 minutes with path coverage enabled)
            PHP_EXTENSION_XDEBUG: 1
            XDEBUG_MODE: coverage
            #PHP_EXTENSION_PCOV: 1
            PHP_EXTENSION_APCU: 0
            PHP_EXTENSION_REDIS: 0
            PHP_EXTENSION_SQLITE3: 1
            PHP_EXTENSION_PDO_MYSQL: 1
            PHP_EXTENSION_PDO_PGSQL: 1
            PHP_EXTENSION_PDO_SQLITE: 1
            PHP_INI_MEMORY_LIMIT: 1g
            PHP_INI_ERROR_REPORTING: E_ALL
            SQUIRREL_CONNECTION_USER: 'user'
            SQUIRREL_CONNECTION_PASSWORD: 'password'
            SQUIRREL_CONNECTION_ROOT_PASSWORD: 'whatever'
            SQUIRREL_CONNECTION_DBNAME: 'shop'
            SQUIRREL_CONNECTION_HOST_MYSQL: 'squirrel_queries_mysql'
            SQUIRREL_CONNECTION_HOST_MARIADB: 'squirrel_queries_mariadb'
            SQUIRREL_CONNECTION_HOST_POSTGRES: 'squirrel_queries_postgres'
            COMPOSER_ROOT_VERSION: 'dev-master'
            STARTUP_COMMAND_1: composer --no-interaction --no-progress --no-scripts --no-plugins --quiet update
            STARTUP_COMMAND_2: rm -rf /usr/src/app/tests/_reports/*
        depends_on:
            - postgres
            - mysql
            - mariadb

    postgres:
        image: postgres:latest
        container_name: squirrel_queries_postgres
        environment:
            POSTGRES_DB: 'shop'
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'

    mysql:
        image: mysql/mysql-server:latest
        container_name: squirrel_queries_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'whatever'
            MYSQL_DATABASE: 'shop'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'

    mariadb:
        image: mariadb:latest
        container_name: squirrel_queries_mariadb
        environment:
            MARIADB_ROOT_PASSWORD: 'whatever'
            MARIADB_DATABASE: 'shop'
            MARIADB_USER: 'user'
            MARIADB_PASSWORD: 'password'